package cn.thd.pojo.checklist;

import java.util.Date;

/**
 * cn.thd.pojo.checklist.ChecklistImplBatch entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class ChecklistImplBatch implements java.io.Serializable {
	//PK   
	private java.lang.String id;
	// 
	private java.lang.String checkBatch;
	// 
	private java.lang.String checkUser;
	// 
	private java.lang.String checkModule;
	//项目ID 项目ID
	private java.lang.String projectId;
	private java.lang.String traceId;
	// 
	private java.lang.String checkedUser;
	private java.lang.String checklistId;
	public java.lang.String getChecklistId() {
		return checklistId;
	}
	public void setChecklistId(java.lang.String checklistId) {
		this.checklistId = checklistId;
	}
	// 
	private java.util.Date checkTime;
	// 
	private java.lang.String isDelete;
	// 
	private java.lang.String checkDesc;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setCheckBatch(java.lang.String checkBatch){
		this.checkBatch = checkBatch;
	}
	public java.lang.String getCheckBatch(){
		return this.checkBatch;
	}
	public void setCheckUser(java.lang.String checkUser){
		this.checkUser = checkUser;
	}
	public java.lang.String getCheckUser(){
		return this.checkUser;
	}
	public void setCheckModule(java.lang.String checkModule){
		this.checkModule = checkModule;
	}
	public java.lang.String getCheckModule(){
		return this.checkModule;
	}
	public void setCheckedUser(java.lang.String checkedUser){
		this.checkedUser = checkedUser;
	}
	public java.lang.String getCheckedUser(){
		return this.checkedUser;
	}
	public void setCheckTime(java.util.Date checkTime){
		this.checkTime = checkTime;
	}
	public java.util.Date getCheckTime(){
		return this.checkTime;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	public void setCheckDesc(java.lang.String checkDesc){
		this.checkDesc = checkDesc;
	}
	public java.lang.String getCheckDesc(){
		return this.checkDesc;
	}
	public java.lang.String getTraceId() {
		return traceId;
	}
	public void setTraceId(java.lang.String traceId) {
		this.traceId = traceId;
	}
	public java.lang.String getProjectId() {
		return projectId;
	}
	public void setProjectId(java.lang.String projectId) {
		this.projectId = projectId;
	}
	
	

}