package cn.thd.pojo.checklist;

import java.util.Date;

/**
 * cn.thd.pojo.checklist.ChecklistImplResult entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class ChecklistImplResult implements java.io.Serializable {
	//PK   
	private java.lang.String id;
	// 
	private java.lang.String checklistId;
	// 
	private java.lang.String checkBatch;
	// 
	private java.lang.String checkRes;
	// 
	private java.lang.String checkDesc;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setChecklistId(java.lang.String checklistId){
		this.checklistId = checklistId;
	}
	public java.lang.String getChecklistId(){
		return this.checklistId;
	}
	public void setCheckBatch(java.lang.String checkBatch){
		this.checkBatch = checkBatch;
	}
	public java.lang.String getCheckBatch(){
		return this.checkBatch;
	}
	public void setCheckRes(java.lang.String checkRes){
		this.checkRes = checkRes;
	}
	public java.lang.String getCheckRes(){
		return this.checkRes;
	}
	public void setCheckDesc(java.lang.String checkDesc){
		this.checkDesc = checkDesc;
	}
	public java.lang.String getCheckDesc(){
		return this.checkDesc;
	}
	
	

}