package cn.thd.pojo.checklist;

import java.util.Date;

/**
 * cn.thd.pojo.se.Checklist entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class Checklist implements java.io.Serializable {
	//PK   
	private java.lang.String id;
	// 
	private java.lang.String treeCode;
	private java.lang.String parentId;
	// 
	private java.lang.String cklistName;
	// 
	private java.lang.String cklistDesc;
	// 
	private java.lang.String cklistContent;
	// 
	private java.lang.String isLeaf;
	// 
	private java.lang.String isValid;
	// 
	private java.lang.String isDelete;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setTreeCode(java.lang.String treeCode){
		this.treeCode = treeCode;
	}
	public java.lang.String getTreeCode(){
		return this.treeCode;
	}
	public void setCklistName(java.lang.String cklistName){
		this.cklistName = cklistName;
	}
	public java.lang.String getCklistName(){
		return this.cklistName;
	}
	public void setCklistDesc(java.lang.String cklistDesc){
		this.cklistDesc = cklistDesc;
	}
	public java.lang.String getCklistDesc(){
		return this.cklistDesc;
	}
	public void setCklistContent(java.lang.String cklistContent){
		this.cklistContent = cklistContent;
	}
	public java.lang.String getCklistContent(){
		return this.cklistContent;
	}
	public void setIsLeaf(java.lang.String isLeaf){
		this.isLeaf = isLeaf;
	}
	public java.lang.String getIsLeaf(){
		return this.isLeaf;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	public java.lang.String getParentId() {
		return parentId;
	}
	public void setParentId(java.lang.String parentId) {
		this.parentId = parentId;
	}
	
	

}