package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeAuth entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeAuth implements java.io.Serializable {
	//PK  标记 标记
	private java.lang.String authCode;
	//说明 说明
	private java.lang.String authDesc;
	
	public void setAuthCode(java.lang.String authCode){
		this.authCode = authCode;
	}
	public java.lang.String getAuthCode(){
		return this.authCode;
	}
	public void setAuthDesc(java.lang.String authDesc){
		this.authDesc = authDesc;
	}
	public java.lang.String getAuthDesc(){
		return this.authDesc;
	}
	
	

}