package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeMapProjectUser entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeMapProjectUser implements java.io.Serializable {
	//PK   
	private java.lang.String rid;
	//项目ID 项目ID
	private java.lang.String projectId;
	//用户ID 用户ID
	private java.lang.String userId;
	//用户姓名 用户姓名
	private java.lang.String userName;
	//个人成本 个人成本
	private java.lang.Float userCost;
	//岗位 岗位
	private java.lang.String userPos;
	//用户级别 用户级别
	private java.lang.String userLevel;
	//计划到港日期 计划到港日期
	private java.util.Date planDuty;
	//计划离岗日期 计划离岗日期
	private java.util.Date planUnduty;
	//实际到岗日期 实际到岗日期
	private java.util.Date actDuty;
	//实际离岗日期 实际离岗日期
	private java.util.Date actUnduty;
	private java.lang.String onPosition;
	
	public void setRid(java.lang.String rid){
		this.rid = rid;
	}
	public java.lang.String getRid(){
		return this.rid;
	}
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	public void setUserId(java.lang.String userId){
		this.userId = userId;
	}
	public java.lang.String getUserId(){
		return this.userId;
	}
	public void setUserName(java.lang.String userName){
		this.userName = userName;
	}
	public java.lang.String getUserName(){
		return this.userName;
	}
	public void setUserCost(java.lang.Float userCost){
		this.userCost = userCost;
	}
	public java.lang.Float getUserCost(){
		return this.userCost;
	}
	public void setUserPos(java.lang.String userPos){
		this.userPos = userPos;
	}
	public java.lang.String getUserPos(){
		return this.userPos;
	}
	public void setUserLevel(java.lang.String userLevel){
		this.userLevel = userLevel;
	}
	public java.lang.String getUserLevel(){
		return this.userLevel;
	}
	public void setPlanDuty(java.util.Date planDuty){
		this.planDuty = planDuty;
	}
	public java.util.Date getPlanDuty(){
		return this.planDuty;
	}
	public void setPlanUnduty(java.util.Date planUnduty){
		this.planUnduty = planUnduty;
	}
	public java.util.Date getPlanUnduty(){
		return this.planUnduty;
	}
	public void setActDuty(java.util.Date actDuty){
		this.actDuty = actDuty;
	}
	public java.util.Date getActDuty(){
		return this.actDuty;
	}
	public void setActUnduty(java.util.Date actUnduty){
		this.actUnduty = actUnduty;
	}
	public java.util.Date getActUnduty(){
		return this.actUnduty;
	}
	public java.lang.String getOnPosition() {
		return onPosition;
	}
	public void setOnPosition(java.lang.String onPosition) {
		this.onPosition = onPosition;
	}
	
	

}