package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeMapUser entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeMapUser implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String id;
	//用户ID 用户ID
	private java.lang.String userId;
	//相关表 相关表
	private java.lang.String relaTab;
	//相关表的数据ID 相关表的数据ID
	private java.lang.String tabKeyValue;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setUserId(java.lang.String userId){
		this.userId = userId;
	}
	public java.lang.String getUserId(){
		return this.userId;
	}
	public void setRelaTab(java.lang.String relaTab){
		this.relaTab = relaTab;
	}
	public java.lang.String getRelaTab(){
		return this.relaTab;
	}
	public void setTabKeyValue(java.lang.String tabKeyValue){
		this.tabKeyValue = tabKeyValue;
	}
	public java.lang.String getTabKeyValue(){
		return this.tabKeyValue;
	}
	
	

}