package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeMapUserRole entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeMapUserRole implements java.io.Serializable {
	//PK   
	private java.lang.String id;
	// 
	private java.lang.String userId;
	// 
	private java.lang.String roleCode;
	// 
	private java.lang.String projectId;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setUserId(java.lang.String userId){
		this.userId = userId;
	}
	public java.lang.String getUserId(){
		return this.userId;
	}
	public void setRoleCode(java.lang.String roleCode){
		this.roleCode = roleCode;
	}
	public java.lang.String getRoleCode(){
		return this.roleCode;
	}
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	
	

}