package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeMapRoleMenu entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeMapRoleMenu implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String id;
	//角色CODE 角色CODE
	private java.lang.String roleCode;
	//菜单ID 菜单ID
	private java.lang.String menuId;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setRoleCode(java.lang.String roleCode){
		this.roleCode = roleCode;
	}
	public java.lang.String getRoleCode(){
		return this.roleCode;
	}
	public void setMenuId(java.lang.String menuId){
		this.menuId = menuId;
	}
	public java.lang.String getMenuId(){
		return this.menuId;
	}
	
	

}