package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeMapRoleAuth entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeMapRoleAuth implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String id;
	//角色CODE 角色CODE
	private java.lang.String roleCode;
	//权限CODE 权限CODE
	private java.lang.String authCode;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setRoleCode(java.lang.String roleCode){
		this.roleCode = roleCode;
	}
	public java.lang.String getRoleCode(){
		return this.roleCode;
	}
	public void setAuthCode(java.lang.String authCode){
		this.authCode = authCode;
	}
	public java.lang.String getAuthCode(){
		return this.authCode;
	}
	
	

}