package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeMeetingRecord entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeMeetingRecord implements java.io.Serializable {
	//PK  条目ID 条目ID
	private java.lang.String itemId;
	//会议CODE 会议CODE
	private java.lang.String meetingCode;
	//提出人 提出人
	private java.lang.String itemIssuer;
	//分类 分类
	private java.lang.String itemClassify;
	//描述 描述
	private java.lang.String itemDesc;
	//执行人 执行人
	private java.lang.String itemPerformer;
	//状态 状态
	private java.lang.String itemStatus;
	//是否删除 是否删除
	private java.lang.String isDelete;
	
	public void setItemId(java.lang.String itemId){
		this.itemId = itemId;
	}
	public java.lang.String getItemId(){
		return this.itemId;
	}
	public void setMeetingCode(java.lang.String meetingCode){
		this.meetingCode = meetingCode;
	}
	public java.lang.String getMeetingCode(){
		return this.meetingCode;
	}
	public void setItemIssuer(java.lang.String itemIssuer){
		this.itemIssuer = itemIssuer;
	}
	public java.lang.String getItemIssuer(){
		return this.itemIssuer;
	}
	public void setItemClassify(java.lang.String itemClassify){
		this.itemClassify = itemClassify;
	}
	public java.lang.String getItemClassify(){
		return this.itemClassify;
	}
	public void setItemDesc(java.lang.String itemDesc){
		this.itemDesc = itemDesc;
	}
	public java.lang.String getItemDesc(){
		return this.itemDesc;
	}
	public void setItemPerformer(java.lang.String itemPerformer){
		this.itemPerformer = itemPerformer;
	}
	public java.lang.String getItemPerformer(){
		return this.itemPerformer;
	}
	public void setItemStatus(java.lang.String itemStatus){
		this.itemStatus = itemStatus;
	}
	public java.lang.String getItemStatus(){
		return this.itemStatus;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	
	

}