package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeMenu entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeMenu implements java.io.Serializable {
	//PK  菜单ID 菜单ID
	private java.lang.String menuId;
	//菜单名称 菜单名称
	private java.lang.String menuName;
	//菜单英文名称 菜单英文名称
	private java.lang.String menuNameEn;
	//树形代码 树形代码
	private java.lang.String treeCode;
	//是否叶子节点 是否叶子节点
	private java.lang.String isLeaf;
	//菜单URL 菜单URL
	private java.lang.String menuUrl;
	//功能描述 功能描述
	private java.lang.String menuDesc;
	//是否有效 是否有效
	private java.lang.String isValid;
	//图标样式 图标样式
	private java.lang.String menuIco;
	//打开方式 打开方式
	private java.lang.String openType;
	//父节点ID
	private java.lang.String parentId;
	//排序号
	private java.lang.String menuOrder;
	
	public void setMenuId(java.lang.String menuId){
		this.menuId = menuId;
	}
	public java.lang.String getMenuId(){
		return this.menuId;
	}
	public void setMenuName(java.lang.String menuName){
		this.menuName = menuName;
	}
	public java.lang.String getMenuName(){
		return this.menuName;
	}
	public java.lang.String getMenuNameEn() {
		return menuNameEn;
	}
	public void setMenuNameEn(java.lang.String menuNameEn) {
		this.menuNameEn = menuNameEn;
	}
	public void setTreeCode(java.lang.String treeCode){
		this.treeCode = treeCode;
	}
	public java.lang.String getTreeCode(){
		return this.treeCode;
	}
	public void setIsLeaf(java.lang.String isLeaf){
		this.isLeaf = isLeaf;
	}
	public java.lang.String getIsLeaf(){
		return this.isLeaf;
	}
	public void setMenuUrl(java.lang.String menuUrl){
		this.menuUrl = menuUrl;
	}
	public java.lang.String getMenuUrl(){
		return this.menuUrl;
	}
	public void setMenuDesc(java.lang.String menuDesc){
		this.menuDesc = menuDesc;
	}
	public java.lang.String getMenuDesc(){
		return this.menuDesc;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setMenuIco(java.lang.String menuIco){
		this.menuIco = menuIco;
	}
	public java.lang.String getMenuIco(){
		return this.menuIco;
	}
	public void setOpenType(java.lang.String openType){
		this.openType = openType;
	}
	public java.lang.String getOpenType(){
		return this.openType;
	}
	public java.lang.String getParentId() {
		return parentId;
	}
	public void setParentId(java.lang.String parentId) {
		this.parentId = parentId;
	}
	public java.lang.String getMenuOrder() {
		return menuOrder;
	}
	public void setMenuOrder(java.lang.String menuOrder) {
		this.menuOrder = menuOrder;
	}
	
	

}