package cn.thd.pojo.se;


/**
 * cn.thd.pojo.se.SePersonLog entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SePersonLog implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String plogId;
	//项目ID 项目ID
	private java.lang.String projectId;
	//用户ID 用户ID
	private java.lang.String userId;
	//日志日期 日志日期
	private java.util.Date plogDate;
	//工作量(h) 工作量(h)
	private java.lang.Float plogWorkload;
	//是否请假 是否请假
	private java.lang.String isLeave;
	//工作内容 工作内容
	private java.lang.String plogRemark;
	//任务ID
	private java.lang.String taskId;
	private java.lang.String isDelete;
	private java.util.Date createDate;
	
	public void setPlogId(java.lang.String plogId){
		this.plogId = plogId;
	}
	public java.lang.String getPlogId(){
		return this.plogId;
	}
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	public void setUserId(java.lang.String userId){
		this.userId = userId;
	}
	public java.lang.String getUserId(){
		return this.userId;
	}
	public void setPlogDate(java.util.Date plogDate){
		this.plogDate = plogDate;
	}
	public java.util.Date getPlogDate(){
		return this.plogDate;
	}
	public void setPlogWorkload(java.lang.Float plogWorkload){
		this.plogWorkload = plogWorkload;
	}
	public java.lang.Float getPlogWorkload(){
		return this.plogWorkload;
	}
	public void setIsLeave(java.lang.String isLeave){
		this.isLeave = isLeave;
	}
	public java.lang.String getIsLeave(){
		return this.isLeave;
	}
	public void setPlogRemark(java.lang.String plogRemark){
		this.plogRemark = plogRemark;
	}
	public java.lang.String getPlogRemark(){
		return this.plogRemark;
	}
	
	public java.lang.String getTaskId() {
		return taskId;
	}
	public void setTaskId(java.lang.String taskId) {
		this.taskId = taskId;
	}
	public java.lang.String getIsDelete() {
		return isDelete;
	}
	public void setIsDelete(java.lang.String isDelete) {
		this.isDelete = isDelete;
	}
	public java.util.Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}
	
	

}