package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeProjectInfo entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeProjectInfo implements java.io.Serializable {
	//PK  项目ID 项目ID
	private java.lang.String projectId;
	//项目标号 项目标号
	private java.lang.String proNo;
	//项目名称 项目名称
	private java.lang.String proName;
	//项目描述 项目描述
	private java.lang.String proDescription;
	//项目目标 项目目标
	private java.lang.String proTarget;
	//项目背景 项目背景
	private java.lang.String proBackground;
	//最终交付物 最终交付物
	private java.lang.String finalConsign;
	//项目经理 项目经理
	private java.lang.String proLeader;
	//项目成员 项目成员
	private java.lang.String proMember;
	
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	public void setProNo(java.lang.String proNo){
		this.proNo = proNo;
	}
	public java.lang.String getProNo(){
		return this.proNo;
	}
	public void setProName(java.lang.String proName){
		this.proName = proName;
	}
	public java.lang.String getProName(){
		return this.proName;
	}
	public void setProDescription(java.lang.String proDescription){
		this.proDescription = proDescription;
	}
	public java.lang.String getProDescription(){
		return this.proDescription;
	}
	public void setProTarget(java.lang.String proTarget){
		this.proTarget = proTarget;
	}
	public java.lang.String getProTarget(){
		return this.proTarget;
	}
	public void setProBackground(java.lang.String proBackground){
		this.proBackground = proBackground;
	}
	public java.lang.String getProBackground(){
		return this.proBackground;
	}
	public void setFinalConsign(java.lang.String finalConsign){
		this.finalConsign = finalConsign;
	}
	public java.lang.String getFinalConsign(){
		return this.finalConsign;
	}
	public void setProLeader(java.lang.String proLeader){
		this.proLeader = proLeader;
	}
	public java.lang.String getProLeader(){
		return this.proLeader;
	}
	public void setProMember(java.lang.String proMember){
		this.proMember = proMember;
	}
	public java.lang.String getProMember(){
		return this.proMember;
	}
	
	

}