package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SePubModule entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SePubModule implements java.io.Serializable {
	//PK  组件ID 组件ID
	private java.lang.String moduleId;
	//组件标题 组件标题
	private java.lang.String moduleTitle;
	//组件分类 组件分类
	private java.lang.String moduleClassify;
	//组件方法名 组件方法名
	private java.lang.String moduleName;
	//组件输入 组件输入
	private java.lang.String moduleInput;
	//组件输出 组件输出
	private java.lang.String moduleOutput;
	//组件描述 组件描述
	private java.lang.String moduleDesc;
	//组件所在文件 组件所在文件
	private java.lang.String moduleFile;
	//组件示例 组件示例
	private java.lang.String moduleExample;
	//组件发布日期 组件发布日期
	private java.util.Date moduleDate;
	//组件负责人 组件负责人
	private java.lang.String moduleUser;
	//所属项目 所属项目
	private java.lang.String projectId;
	
	public void setModuleId(java.lang.String moduleId){
		this.moduleId = moduleId;
	}
	public java.lang.String getModuleId(){
		return this.moduleId;
	}
	public void setModuleTitle(java.lang.String moduleTitle){
		this.moduleTitle = moduleTitle;
	}
	public java.lang.String getModuleTitle(){
		return this.moduleTitle;
	}
	public void setModuleClassify(java.lang.String moduleClassify){
		this.moduleClassify = moduleClassify;
	}
	public java.lang.String getModuleClassify(){
		return this.moduleClassify;
	}
	public void setModuleName(java.lang.String moduleName){
		this.moduleName = moduleName;
	}
	public java.lang.String getModuleName(){
		return this.moduleName;
	}
	public void setModuleInput(java.lang.String moduleInput){
		this.moduleInput = moduleInput;
	}
	public java.lang.String getModuleInput(){
		return this.moduleInput;
	}
	public void setModuleOutput(java.lang.String moduleOutput){
		this.moduleOutput = moduleOutput;
	}
	public java.lang.String getModuleOutput(){
		return this.moduleOutput;
	}
	public void setModuleDesc(java.lang.String moduleDesc){
		this.moduleDesc = moduleDesc;
	}
	public java.lang.String getModuleDesc(){
		return this.moduleDesc;
	}
	public void setModuleFile(java.lang.String moduleFile){
		this.moduleFile = moduleFile;
	}
	public java.lang.String getModuleFile(){
		return this.moduleFile;
	}
	public void setModuleExample(java.lang.String moduleExample){
		this.moduleExample = moduleExample;
	}
	public java.lang.String getModuleExample(){
		return this.moduleExample;
	}
	public void setModuleDate(java.util.Date moduleDate){
		this.moduleDate = moduleDate;
	}
	public java.util.Date getModuleDate(){
		return this.moduleDate;
	}
	public void setModuleUser(java.lang.String moduleUser){
		this.moduleUser = moduleUser;
	}
	public java.lang.String getModuleUser(){
		return this.moduleUser;
	}
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	
	

}