package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeRequirementTrace entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeRequirementTrace implements java.io.Serializable {
	//PK  矩阵ID 矩阵ID
	private java.lang.String traceId;
	//项目ID 项目ID
	private java.lang.String projectId;
	//矩阵编号 矩阵编号
	private java.lang.String traceNo;
	//矩阵名称 矩阵名称
	private java.lang.String traceName;
	//树形目录代码 树形目录代码
	private java.lang.String treeCode;
	//是否叶子节点 是否叶子节点
	private java.lang.String isLeaf;
	//排序号 排序号
	private java.lang.Float traceOrder;
	//是否有效 是否有效
	private java.lang.String isValid;
	//是否删除 是否删除
	private java.lang.String isDelete;
	//创建时间 创建时间
	private java.util.Date createTime;
	//更新时间 更新时间
	private java.util.Date updateTime;
	//父节点ID
	private java.lang.String parentId;
	
	public void setTraceId(java.lang.String traceId){
		this.traceId = traceId;
	}
	public java.lang.String getTraceId(){
		return this.traceId;
	}
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	public void setTraceNo(java.lang.String traceNo){
		this.traceNo = traceNo;
	}
	public java.lang.String getTraceNo(){
		return this.traceNo;
	}
	public void setTraceName(java.lang.String traceName){
		this.traceName = traceName;
	}
	public java.lang.String getTraceName(){
		return this.traceName;
	}
	public void setTreeCode(java.lang.String treeCode){
		this.treeCode = treeCode;
	}
	public java.lang.String getTreeCode(){
		return this.treeCode;
	}
	public void setIsLeaf(java.lang.String isLeaf){
		this.isLeaf = isLeaf;
	}
	public java.lang.String getIsLeaf(){
		return this.isLeaf;
	}
	public void setTraceOrder(java.lang.Float traceOrder){
		this.traceOrder = traceOrder;
	}
	public java.lang.Float getTraceOrder(){
		return this.traceOrder;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	public void setUpdateTime(java.util.Date updateTime){
		this.updateTime = updateTime;
	}
	public java.util.Date getUpdateTime(){
		return this.updateTime;
	}
	public java.lang.String getParentId() {
		return parentId;
	}
	public void setParentId(java.lang.String parentId) {
		this.parentId = parentId;
	}
	
	

}