package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeRole entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeRole implements java.io.Serializable {
	//PK  角色Code 角色Code
	private java.lang.String roleCode;
	//角色名称 角色名称
	private java.lang.String roleName;
	//角色等级 角色等级
	private java.lang.String roleLevel;
	//角色分类 角色分类
	private java.lang.String roleClassify;
	//是否有效 是否有效
	private java.lang.String isValid;
	//创建人 创建人
	private java.lang.String creator;
	//创建时间 创建时间
	private java.util.Date createTime;
	//修改人 修改人
	private java.lang.String modifier;
	//修改时间 修改时间
	private java.util.Date modiTime;
	
	public void setRoleCode(java.lang.String roleCode){
		this.roleCode = roleCode;
	}
	public java.lang.String getRoleCode(){
		return this.roleCode;
	}
	public void setRoleName(java.lang.String roleName){
		this.roleName = roleName;
	}
	public java.lang.String getRoleName(){
		return this.roleName;
	}
	public void setRoleLevel(java.lang.String roleLevel){
		this.roleLevel = roleLevel;
	}
	public java.lang.String getRoleLevel(){
		return this.roleLevel;
	}
	public void setRoleClassify(java.lang.String roleClassify){
		this.roleClassify = roleClassify;
	}
	public java.lang.String getRoleClassify(){
		return this.roleClassify;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setCreator(java.lang.String creator){
		this.creator = creator;
	}
	public java.lang.String getCreator(){
		return this.creator;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	public void setModifier(java.lang.String modifier){
		this.modifier = modifier;
	}
	public java.lang.String getModifier(){
		return this.modifier;
	}
	public void setModiTime(java.util.Date modiTime){
		this.modiTime = modiTime;
	}
	public java.util.Date getModiTime(){
		return this.modiTime;
	}
	
	

}