package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeTraceValueString entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeTraceValueString implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String vid;
	//矩阵ID 矩阵ID
	private java.lang.String traceId;
	//属性名称 属性名称
	private java.lang.String kcode;
	//属性类型
	private java.lang.String ktype;
	//值 值
	private java.lang.String v;
	
	public void setVid(java.lang.String vid){
		this.vid = vid;
	}
	public java.lang.String getVid(){
		return this.vid;
	}
	public void setTraceId(java.lang.String traceId){
		this.traceId = traceId;
	}
	public java.lang.String getTraceId(){
		return this.traceId;
	}
	
	public java.lang.String getKcode() {
		return kcode;
	}
	public void setKcode(java.lang.String kcode) {
		this.kcode = kcode;
	}
	public void setV(java.lang.String v){
		this.v = v;
	}
	public java.lang.String getV(){
		return this.v;
	}
	public java.lang.String getKtype() {
		return ktype;
	}
	public void setKtype(java.lang.String ktype) {
		this.ktype = ktype;
	}
	
	

}