package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeTraceDefectRepair entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeTraceDefectRepair implements java.io.Serializable {
	//PK   
	private java.lang.String repairId;
	// 
	private java.lang.String defectId;
	// 
	private java.lang.String operateUser;
	// 
	private java.lang.String operateStatus;
	// 
	private java.lang.String remark;
	// 
	private java.util.Date createTime;
	
	public void setRepairId(java.lang.String repairId){
		this.repairId = repairId;
	}
	public java.lang.String getRepairId(){
		return this.repairId;
	}
	public void setDefectId(java.lang.String defectId){
		this.defectId = defectId;
	}
	public java.lang.String getDefectId(){
		return this.defectId;
	}
	public void setOperateUser(java.lang.String operateUser){
		this.operateUser = operateUser;
	}
	public java.lang.String getOperateUser(){
		return this.operateUser;
	}
	public void setOperateStatus(java.lang.String operateStatus){
		this.operateStatus = operateStatus;
	}
	public java.lang.String getOperateStatus(){
		return this.operateStatus;
	}
	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}
	public java.lang.String getRemark(){
		return this.remark;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	
	

}