package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeTraceKey entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeTraceKey implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String kid;
	//矩阵id 矩阵id
	private java.lang.String traceId;
	//属性名称 属性名称
	private java.lang.String kname;
	//属性代码(小写英文字母) 属性代码(小写英文字母)
	private java.lang.String kcode;
	//属性类型 STRING:字符串 CLOB:大文本 DIC:字典  INT:整数  FLOAT:小数  DATE:日期 属性类型 STRING:字符串 CLOB:大文本 DIC:字典  INT:整数  FLOAT:小数  DATE:日期
	private java.lang.String ktype;
	//属性备注 属性备注
	private java.lang.String kdesc;
	
	public void setKid(java.lang.String kid){
		this.kid = kid;
	}
	public java.lang.String getKid(){
		return this.kid;
	}
	public void setTraceId(java.lang.String traceId){
		this.traceId = traceId;
	}
	public java.lang.String getTraceId(){
		return this.traceId;
	}
	public void setKname(java.lang.String kname){
		this.kname = kname;
	}
	public java.lang.String getKname(){
		return this.kname;
	}
	public void setKcode(java.lang.String kcode){
		this.kcode = kcode;
	}
	public java.lang.String getKcode(){
		return this.kcode;
	}
	public void setKtype(java.lang.String ktype){
		this.ktype = ktype;
	}
	public java.lang.String getKtype(){
		return this.ktype;
	}
	public void setKdesc(java.lang.String kdesc){
		this.kdesc = kdesc;
	}
	public java.lang.String getKdesc(){
		return this.kdesc;
	}
	
	

}