package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeTraceNote entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeTraceNote implements java.io.Serializable {
	//PK  遗留备忘id 遗留备忘id
	private java.lang.String noteId;
	//记事种类  遗留 备忘 缺陷 记事种类  遗留 备忘 缺陷
	private java.lang.String noteType;
	//遗留备忘标题 遗留备忘标题
	private java.lang.String noteTitle;
	//遗留备忘内容 遗留备忘内容
	private java.lang.String noteContent;
	//遗留备忘状态 遗留备忘状态
	private java.lang.String noteStatus;
	//矩阵ID 矩阵ID
	private java.lang.String traceId;
	//提醒日期 提醒日期
	private java.util.Date alarmDate;
	//预警天数 预警天数
	private java.lang.Integer alarmDays;
	//签发人
	private java.lang.String issueUser;
	//执行人
	private java.lang.String exeUser;
	//落实日期
	private java.util.Date resolveDate;
	//是否有效 是否有效 
	private java.lang.String isValid;
	//是否删除 是否删除
	private java.lang.String isDelete;
	//创建时间 创建时间
	private java.util.Date createTime;
	//修改时间 修改时间
	private java.util.Date updateTime;
	
	private java.lang.String creator;
	private java.lang.String modifier;
	
	public java.lang.String getCreator() {
		return creator;
	}
	public void setCreator(java.lang.String creator) {
		this.creator = creator;
	}
	public java.lang.String getModifier() {
		return modifier;
	}
	public void setModifier(java.lang.String modifier) {
		this.modifier = modifier;
	}
	public void setNoteId(java.lang.String noteId){
		this.noteId = noteId;
	}
	public java.lang.String getNoteId(){
		return this.noteId;
	}
	public void setNoteType(java.lang.String noteType){
		this.noteType = noteType;
	}
	public java.lang.String getNoteType(){
		return this.noteType;
	}
	public void setNoteTitle(java.lang.String noteTitle){
		this.noteTitle = noteTitle;
	}
	public java.lang.String getNoteTitle(){
		return this.noteTitle;
	}
	public void setNoteContent(java.lang.String noteContent){
		this.noteContent = noteContent;
	}
	public java.lang.String getNoteContent(){
		return this.noteContent;
	}
	public void setNoteStatus(java.lang.String noteStatus){
		this.noteStatus = noteStatus;
	}
	public java.lang.String getNoteStatus(){
		return this.noteStatus;
	}
	public void setTraceId(java.lang.String traceId){
		this.traceId = traceId;
	}
	public java.lang.String getTraceId(){
		return this.traceId;
	}
	public void setAlarmDate(java.util.Date alarmDate){
		this.alarmDate = alarmDate;
	}
	public java.util.Date getAlarmDate(){
		return this.alarmDate;
	}
	public void setAlarmDays(java.lang.Integer alarmDays){
		this.alarmDays = alarmDays;
	}
	public java.lang.Integer getAlarmDays(){
		return this.alarmDays;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	public void setUpdateTime(java.util.Date updateTime){
		this.updateTime = updateTime;
	}
	public java.util.Date getUpdateTime(){
		return this.updateTime;
	}
	public java.lang.String getExeUser() {
		return exeUser;
	}
	public void setExeUser(java.lang.String exeUser) {
		this.exeUser = exeUser;
	}
	public java.util.Date getResolveDate() {
		return resolveDate;
	}
	public void setResolveDate(java.util.Date resolveDate) {
		this.resolveDate = resolveDate;
	}
	public java.lang.String getIssueUser() {
		return issueUser;
	}
	public void setIssueUser(java.lang.String issueUser) {
		this.issueUser = issueUser;
	}
	
	

}