package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeUser entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeUser implements java.io.Serializable {
	//PK  用户ID 用户ID
	private java.lang.String userId;
	//用户姓名 用户姓名
	private java.lang.String userName;
	//账号
	private java.lang.String userAccount;
	//用户密码 
	private java.lang.String userPassword;
	//所在公司 所在公司
	private java.lang.String companyName;
	//邮箱 邮箱
	private java.lang.String userMail;
	
	public void setUserId(java.lang.String userId){
		this.userId = userId;
	}
	public java.lang.String getUserId(){
		return this.userId;
	}
	public void setUserName(java.lang.String userName){
		this.userName = userName;
	}
	public java.lang.String getUserName(){
		return this.userName;
	}
	public void setCompanyName(java.lang.String companyName){
		this.companyName = companyName;
	}
	public java.lang.String getCompanyName(){
		return this.companyName;
	}
	public void setUserMail(java.lang.String userMail){
		this.userMail = userMail;
	}
	public java.lang.String getUserMail(){
		return this.userMail;
	}
	public java.lang.String getUserPassword() {
		return userPassword;
	}
	public void setUserPassword(java.lang.String userPassword) {
		this.userPassword = userPassword;
	}
	public java.lang.String getUserAccount() {
		return userAccount;
	}
	public void setUserAccount(java.lang.String userAccount) {
		this.userAccount = userAccount;
	}
	
	

}