package cn.thd.pojo.se;

import java.util.Date;

/**
 * cn.thd.pojo.se.SeUserRewardAmerce entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeUserRewardAmerce implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String id;
	//所属系统 所属系统
	private java.lang.String projectId;
	//用户ID 用户ID
	private java.lang.String userId;
	//登记 登记
	private java.lang.String raLevel;
	//备注 备注
	private java.lang.String remark;
	//是否删除 是否删除
	private java.lang.String isDelete;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	public void setUserId(java.lang.String userId){
		this.userId = userId;
	}
	public java.lang.String getUserId(){
		return this.userId;
	}
	public void setRaLevel(java.lang.String raLevel){
		this.raLevel = raLevel;
	}
	public java.lang.String getRaLevel(){
		return this.raLevel;
	}
	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}
	public java.lang.String getRemark(){
		return this.remark;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	
	

}