package cn.thd.pojo.vita;

import java.util.Date;

/**
 * cn.thd.pojo.vita.VitaProjectDuty entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class VitaProjectDuty implements java.io.Serializable {
	//PK   
	private java.lang.String dutyId;
	// 
	private java.lang.String projectHisId;
	// 
	private java.lang.String dutyDesc;
	// 
	private java.lang.String isValid;
	// 
	private java.util.Date createTime;
	
	public void setDutyId(java.lang.String dutyId){
		this.dutyId = dutyId;
	}
	public java.lang.String getDutyId(){
		return this.dutyId;
	}
	public void setProjectHisId(java.lang.String projectHisId){
		this.projectHisId = projectHisId;
	}
	public java.lang.String getProjectHisId(){
		return this.projectHisId;
	}
	public void setDutyDesc(java.lang.String dutyDesc){
		this.dutyDesc = dutyDesc;
	}
	public java.lang.String getDutyDesc(){
		return this.dutyDesc;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	
	

}