package cn.thd.pojo.common;

import java.util.Date;

/**
 * cn.thd.pojo.common.SeAttach entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeAttach implements java.io.Serializable {
	//PK  附件ID 附件ID
	private java.lang.String attachId;
	//外键ID 外键ID
	private java.lang.String fid;
	//外键分类 外键分类
	private java.lang.String fkey;
	//附件名称 附件名称
	private java.lang.String attachName;
	//附件位置 附件位置
	private java.lang.String attachPath;
	//文件大小 文件大小
	private java.lang.Long attachSize;
	//上传时间 上传时间
	private java.util.Date createTime;
	//文件后缀 文件后缀
	private java.lang.String attachFix;
	//上传人 上传人
	private java.lang.String uploader;
	//是否有效 是否有效
	private java.lang.String isValid;
	
	public void setAttachId(java.lang.String attachId){
		this.attachId = attachId;
	}
	public java.lang.String getAttachId(){
		return this.attachId;
	}
	public void setFid(java.lang.String fid){
		this.fid = fid;
	}
	public java.lang.String getFid(){
		return this.fid;
	}
	public void setFkey(java.lang.String fkey){
		this.fkey = fkey;
	}
	public java.lang.String getFkey(){
		return this.fkey;
	}
	public void setAttachName(java.lang.String attachName){
		this.attachName = attachName;
	}
	public java.lang.String getAttachName(){
		return this.attachName;
	}
	public void setAttachPath(java.lang.String attachPath){
		this.attachPath = attachPath;
	}
	public java.lang.String getAttachPath(){
		return this.attachPath;
	}
	public void setAttachSize(java.lang.Long attachSize){
		this.attachSize = attachSize;
	}
	public java.lang.Long getAttachSize(){
		return this.attachSize;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	public void setAttachFix(java.lang.String attachFix){
		this.attachFix = attachFix;
	}
	public java.lang.String getAttachFix(){
		return this.attachFix;
	}
	public void setUploader(java.lang.String uploader){
		this.uploader = uploader;
	}
	public java.lang.String getUploader(){
		return this.uploader;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	
	

}