package cn.thd.pojo.common;


/**
 * cn.thd.pojo.se.SysDay entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysDay implements java.io.Serializable {
	//PK   
	private java.lang.String id;
	// 
	private java.util.Date day;
	// 
	private java.lang.String status;
	
	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setDay(java.util.Date day){
		this.day = day;
	}
	public java.util.Date getDay(){
		return this.day;
	}
	public void setStatus(java.lang.String status){
		this.status = status;
	}
	public java.lang.String getStatus(){
		return this.status;
	}
	
	

}