package cn.thd.pojo.common;

import java.util.Date;

/**
 * cn.thd.pojo.common.SysDicProcess entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysDicProcess implements java.io.Serializable {
	//PK  l流程ID l流程ID
	private java.lang.String processId;
	//流程KEY 流程KEY
	private java.lang.String processKey;
	//流程名称 流程名称
	private java.lang.String processName;
	//流程定义ID 流程定义ID
	private java.lang.String processDefId;
	//流程service 流程service
	private java.lang.String processService;
	//是否删除 是否删除
	private java.lang.String isDelete;
	
	public void setProcessId(java.lang.String processId){
		this.processId = processId;
	}
	public java.lang.String getProcessId(){
		return this.processId;
	}
	public void setProcessKey(java.lang.String processKey){
		this.processKey = processKey;
	}
	public java.lang.String getProcessKey(){
		return this.processKey;
	}
	public void setProcessName(java.lang.String processName){
		this.processName = processName;
	}
	public java.lang.String getProcessName(){
		return this.processName;
	}
	
	public java.lang.String getProcessDefId() {
		return processDefId;
	}
	public void setProcessDefId(java.lang.String processDefId) {
		this.processDefId = processDefId;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	public java.lang.String getProcessService() {
		return processService;
	}
	public void setProcessService(java.lang.String processService) {
		this.processService = processService;
	}
	
	

}