package cn.thd.pojo.common;

import java.util.Date;

/**
 * cn.thd.pojo.common.SysDicStandardDoc entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysDicStandardDoc implements java.io.Serializable {
	//PK  文档CODE 文档CODE
	private java.lang.String docCode;
	//标准文档名称 标准文档名称
	private java.lang.String docName;
	//所属项目阶段 所属项目阶段
	private java.lang.String docPhases;
	//标准文档说明 标准文档说明
	private java.lang.String docDesc;
	//标准文档模板 标准文档模板
	private java.lang.String docBlankTemplate;
	//标准文档样例 标准文档样例
	private java.lang.String docExample;
	//是否删除 是否删除
	private java.lang.String isDelete;
	
	public void setDocCode(java.lang.String docCode){
		this.docCode = docCode;
	}
	public java.lang.String getDocCode(){
		return this.docCode;
	}
	public void setDocName(java.lang.String docName){
		this.docName = docName;
	}
	public java.lang.String getDocName(){
		return this.docName;
	}
	public void setDocPhases(java.lang.String docPhases){
		this.docPhases = docPhases;
	}
	public java.lang.String getDocPhases(){
		return this.docPhases;
	}
	public void setDocDesc(java.lang.String docDesc){
		this.docDesc = docDesc;
	}
	public java.lang.String getDocDesc(){
		return this.docDesc;
	}
	public void setDocBlankTemplate(java.lang.String docBlankTemplate){
		this.docBlankTemplate = docBlankTemplate;
	}
	public java.lang.String getDocBlankTemplate(){
		return this.docBlankTemplate;
	}
	public void setDocExample(java.lang.String docExample){
		this.docExample = docExample;
	}
	public java.lang.String getDocExample(){
		return this.docExample;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	
	

}