package cn.thd.pojo.common;

import java.util.Date;

/**
 * cn.thd.pojo.common.SysDicFunction entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysDicFunction implements java.io.Serializable {
	//PK  功能主键 功能主键
	private java.lang.String funId;
	//功能名称 功能名称
	private java.lang.String funName;
	//功能URL 功能URL
	private java.lang.String funUrl;
	//功能描述 功能描述
	private java.lang.String funDesc;
	//是否有效 是否有效
	private java.lang.String isValid;
	//是否删除 是否删除
	private java.lang.String isDelete;
	
	public void setFunId(java.lang.String funId){
		this.funId = funId;
	}
	public java.lang.String getFunId(){
		return this.funId;
	}
	public void setFunName(java.lang.String funName){
		this.funName = funName;
	}
	public java.lang.String getFunName(){
		return this.funName;
	}
	public void setFunUrl(java.lang.String funUrl){
		this.funUrl = funUrl;
	}
	public java.lang.String getFunUrl(){
		return this.funUrl;
	}
	public void setFunDesc(java.lang.String funDesc){
		this.funDesc = funDesc;
	}
	public java.lang.String getFunDesc(){
		return this.funDesc;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	
	

}