package cn.thd.pojo.common;

import java.util.Date;

/**
 * cn.thd.pojo.se.SysDicPub entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysDicPub implements java.io.Serializable {
	//PK   
	private java.lang.String dicId;
	// 
	private java.lang.String dicClassify;
	// 
	private java.lang.String dicName;
	// 
	private java.lang.String dicDesc;
	
	public void setDicId(java.lang.String dicId){
		this.dicId = dicId;
	}
	public java.lang.String getDicId(){
		return this.dicId;
	}
	public void setDicClassify(java.lang.String dicClassify){
		this.dicClassify = dicClassify;
	}
	public java.lang.String getDicClassify(){
		return this.dicClassify;
	}
	public void setDicName(java.lang.String dicName){
		this.dicName = dicName;
	}
	public java.lang.String getDicName(){
		return this.dicName;
	}
	public void setDicDesc(java.lang.String dicDesc){
		this.dicDesc = dicDesc;
	}
	public java.lang.String getDicDesc(){
		return this.dicDesc;
	}
	
	

}