package cn.thd.pojo.common;

import java.util.Date;

/**
 * cn.thd.pojo.common.SysDicProcessStep entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysDicProcessStep implements java.io.Serializable {
	//PK  步骤ID 步骤ID
	private java.lang.String stepId;
	//所属流程ID 所属流程ID
	private java.lang.String processId;
	//步骤CODE 步骤CODE
	private java.lang.String stepCode;
	//步骤名称 步骤名称
	private java.lang.String stepName;
	//步骤序号 步骤序号
	private java.lang.Integer stepOrder;
	//是否第一步骤 是否第一步骤
	private java.lang.String isFirstStep;
	//是否最后一个步骤 是否最后一个步骤
	private java.lang.String isLastStep;
	//是否删除 是否删除
	private java.lang.String isDelete;
	
	public void setStepId(java.lang.String stepId){
		this.stepId = stepId;
	}
	public java.lang.String getStepId(){
		return this.stepId;
	}
	public void setProcessId(java.lang.String processId){
		this.processId = processId;
	}
	public java.lang.String getProcessId(){
		return this.processId;
	}
	public void setStepCode(java.lang.String stepCode){
		this.stepCode = stepCode;
	}
	public java.lang.String getStepCode(){
		return this.stepCode;
	}
	public void setStepName(java.lang.String stepName){
		this.stepName = stepName;
	}
	public java.lang.String getStepName(){
		return this.stepName;
	}
	public void setStepOrder(java.lang.Integer stepOrder){
		this.stepOrder = stepOrder;
	}
	public java.lang.Integer getStepOrder(){
		return this.stepOrder;
	}
	public void setIsFirstStep(java.lang.String isFirstStep){
		this.isFirstStep = isFirstStep;
	}
	public java.lang.String getIsFirstStep(){
		return this.isFirstStep;
	}
	public void setIsLastStep(java.lang.String isLastStep){
		this.isLastStep = isLastStep;
	}
	public java.lang.String getIsLastStep(){
		return this.isLastStep;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	
	

}