package cn.thd.pojo.common;

import java.util.Date;

/**
 * cn.thd.pojo.common.SysTimerList entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysTimerList implements java.io.Serializable {
	//PK  主键 主键
	private java.lang.String timerId;
	//标识 标识
	private java.lang.String timerCode;
	//所属组 所属组
	private java.lang.String timerGroup;
	//名称 名称
	private java.lang.String timerName;
	//描述 描述
	private java.lang.String timerDesc;
	//类全名 类全名
	private java.lang.String timerClassName;
	//执行计划 执行计划
	private java.lang.String executionPlan;
	//是否删除 是否删除
	private java.lang.String isDelete;
	//创建时间 创建时间
	private java.util.Date createTime;
	//启动方式 启动方式  1自动 2手工
	private java.lang.String startType;
	
	public void setTimerId(java.lang.String timerId){
		this.timerId = timerId;
	}
	public java.lang.String getTimerId(){
		return this.timerId;
	}
	public void setTimerCode(java.lang.String timerCode){
		this.timerCode = timerCode;
	}
	public java.lang.String getTimerCode(){
		return this.timerCode;
	}
	public void setTimerGroup(java.lang.String timerGroup){
		this.timerGroup = timerGroup;
	}
	public java.lang.String getTimerGroup(){
		return this.timerGroup;
	}
	public void setTimerName(java.lang.String timerName){
		this.timerName = timerName;
	}
	public java.lang.String getTimerName(){
		return this.timerName;
	}
	public void setTimerDesc(java.lang.String timerDesc){
		this.timerDesc = timerDesc;
	}
	public java.lang.String getTimerDesc(){
		return this.timerDesc;
	}
	public void setTimerClassName(java.lang.String timerClassName){
		this.timerClassName = timerClassName;
	}
	public java.lang.String getTimerClassName(){
		return this.timerClassName;
	}
	public void setExecutionPlan(java.lang.String executionPlan){
		this.executionPlan = executionPlan;
	}
	public java.lang.String getExecutionPlan(){
		return this.executionPlan;
	}
	public void setIsDelete(java.lang.String isDelete){
		this.isDelete = isDelete;
	}
	public java.lang.String getIsDelete(){
		return this.isDelete;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	public void setStartType(java.lang.String startType){
		this.startType = startType;
	}
	public java.lang.String getStartType(){
		return this.startType;
	}
	
	

}