package cn.thd.pojo.sys;

import java.util.Date;

/**
 * cn.thd.pojo.se.SysNo entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SysNo implements java.io.Serializable {
	//PK   
	private java.lang.String noId;
	// 
	private java.lang.String noKey;
	// 
	private java.lang.Integer noCount;
	
	public void setNoId(java.lang.String noId){
		this.noId = noId;
	}
	public java.lang.String getNoId(){
		return this.noId;
	}
	public void setNoKey(java.lang.String noKey){
		this.noKey = noKey;
	}
	public java.lang.String getNoKey(){
		return this.noKey;
	}
	public void setNoCount(java.lang.Integer noCount){
		this.noCount = noCount;
	}
	public java.lang.Integer getNoCount(){
		return this.noCount;
	}
	
	

}