package cn.thd.pojo.vita;

import java.util.Date;

/**
 * cn.thd.pojo.vita.VitaProjectHis entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class VitaProjectHis implements java.io.Serializable {
	//PK   
	private java.lang.String projectHisId;
	// 
	private java.lang.String workHisId;
	// 
	private java.lang.String projectName;
	// 
	private java.lang.String position;
	// 
	private java.lang.String duty;
	// 
	private java.util.Date beginDate;
	// 
	private java.util.Date finishDate;
	// 
	private java.lang.String projectDesc;
	// 
	private java.lang.String isValid;
	// 
	private java.util.Date createTime;
	
	public void setProjectHisId(java.lang.String projectHisId){
		this.projectHisId = projectHisId;
	}
	public java.lang.String getProjectHisId(){
		return this.projectHisId;
	}
	public void setWorkHisId(java.lang.String workHisId){
		this.workHisId = workHisId;
	}
	public java.lang.String getWorkHisId(){
		return this.workHisId;
	}
	public void setProjectName(java.lang.String projectName){
		this.projectName = projectName;
	}
	public java.lang.String getProjectName(){
		return this.projectName;
	}
	public void setPosition(java.lang.String position){
		this.position = position;
	}
	public java.lang.String getPosition(){
		return this.position;
	}
	public void setDuty(java.lang.String duty){
		this.duty = duty;
	}
	public java.lang.String getDuty(){
		return this.duty;
	}
	public void setBeginDate(java.util.Date beginDate){
		this.beginDate = beginDate;
	}
	public java.util.Date getBeginDate(){
		return this.beginDate;
	}
	public void setFinishDate(java.util.Date finishDate){
		this.finishDate = finishDate;
	}
	public java.util.Date getFinishDate(){
		return this.finishDate;
	}
	public void setProjectDesc(java.lang.String projectDesc){
		this.projectDesc = projectDesc;
	}
	public java.lang.String getProjectDesc(){
		return this.projectDesc;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	
	

}