package cn.thd.pojo.vita;

import java.util.Date;

/**
 * cn.thd.pojo.vita.VitaProjectTec entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class VitaProjectTec implements java.io.Serializable {
	//PK   
	private java.lang.String projectTecId;
	// 
	private java.lang.String projectHisId;
	// 
	private java.lang.String tecName;
	// 
	private java.lang.String tecClassify;
	// 
	private java.lang.String isValid;
	// 
	private java.util.Date createTime;
	
	public void setProjectTecId(java.lang.String projectTecId){
		this.projectTecId = projectTecId;
	}
	public java.lang.String getProjectTecId(){
		return this.projectTecId;
	}
	public void setProjectHisId(java.lang.String projectHisId){
		this.projectHisId = projectHisId;
	}
	public java.lang.String getProjectHisId(){
		return this.projectHisId;
	}
	public void setTecName(java.lang.String tecName){
		this.tecName = tecName;
	}
	public java.lang.String getTecName(){
		return this.tecName;
	}
	public void setTecClassify(java.lang.String tecClassify){
		this.tecClassify = tecClassify;
	}
	public java.lang.String getTecClassify(){
		return this.tecClassify;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	
	

}