package cn.thd.pojo.vita;

import java.util.Date;

/**
 * cn.thd.pojo.vita.VitaWorkHis entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class VitaWorkHis implements java.io.Serializable {
	//PK   
	private java.lang.String workHisId;
	// 
	private java.lang.String vitaId;
	// 
	private java.lang.String companyName;
	// 
	private java.util.Date beginDate;
	// 
	private java.util.Date finishDate;
	// 
	private java.lang.String companyScale;
	// 
	private java.lang.String isValid;
	// 
	private java.util.Date createTime;
	
	public void setWorkHisId(java.lang.String workHisId){
		this.workHisId = workHisId;
	}
	public java.lang.String getWorkHisId(){
		return this.workHisId;
	}
	public void setVitaId(java.lang.String vitaId){
		this.vitaId = vitaId;
	}
	public java.lang.String getVitaId(){
		return this.vitaId;
	}
	public void setCompanyName(java.lang.String companyName){
		this.companyName = companyName;
	}
	public java.lang.String getCompanyName(){
		return this.companyName;
	}
	public void setBeginDate(java.util.Date beginDate){
		this.beginDate = beginDate;
	}
	public java.util.Date getBeginDate(){
		return this.beginDate;
	}
	public void setFinishDate(java.util.Date finishDate){
		this.finishDate = finishDate;
	}
	public java.util.Date getFinishDate(){
		return this.finishDate;
	}
	public void setCompanyScale(java.lang.String companyScale){
		this.companyScale = companyScale;
	}
	public java.lang.String getCompanyScale(){
		return this.companyScale;
	}
	public void setIsValid(java.lang.String isValid){
		this.isValid = isValid;
	}
	public java.lang.String getIsValid(){
		return this.isValid;
	}
	public void setCreateTime(java.util.Date createTime){
		this.createTime = createTime;
	}
	public java.util.Date getCreateTime(){
		return this.createTime;
	}
	
	

}