package cn.thd.pojo.process;

import java.util.List;

/**
 * cn.thd.pojo.process.SeProcTask entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class SeProcTask implements java.io.Serializable {
	//PK   
	private java.lang.String jobno;
	// 
	private java.lang.String assigner;
	private java.lang.String taskName;
	private java.lang.String taskId;
	private java.lang.String taskRequire;
	// 
	private java.lang.String performInfo;
	// 
	private java.lang.String auditInfo;
	// 
	private java.lang.String backlogId;
	
	private java.lang.String projectId;
	
	//额外属性
	private List performer;
	//额外属性
	private List auditer;
	//额外属性
	private String performerNames;
	//额外属性
	private String auditerNames;
	
	
	
	
	public void setJobno(java.lang.String jobno){
		this.jobno = jobno;
	}
	public java.lang.String getJobno(){
		return this.jobno;
	}
	public void setAssigner(java.lang.String assigner){
		this.assigner = assigner;
	}
	public java.lang.String getAssigner(){
		return this.assigner;
	}
	public void setPerformInfo(java.lang.String performInfo){
		this.performInfo = performInfo;
	}
	public java.lang.String getPerformInfo(){
		return this.performInfo;
	}
	public void setAuditInfo(java.lang.String auditInfo){
		this.auditInfo = auditInfo;
	}
	public java.lang.String getAuditInfo(){
		return this.auditInfo;
	}
	public void setBacklogId(java.lang.String backlogId){
		this.backlogId = backlogId;
	}
	public java.lang.String getBacklogId(){
		return this.backlogId;
	}
	public java.lang.String getTaskName() {
		return taskName;
	}
	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}
	
	public java.lang.String getTaskId() {
		return taskId;
	}
	public void setTaskId(java.lang.String taskId) {
		this.taskId = taskId;
	}
	public java.lang.String getTaskRequire() {
		return taskRequire;
	}
	public void setTaskRequire(java.lang.String taskRequire) {
		this.taskRequire = taskRequire;
	}
	public List getPerformer() {
		return performer;
	}
	public void setPerformer(List performer) {
		this.performer = performer;
	}
	public List getAuditer() {
		return auditer;
	}
	public void setAuditer(List auditer) {
		this.auditer = auditer;
	}
	public String getPerformerNames() {
		return performerNames;
	}
	public void setPerformerNames(String performerNames) {
		this.performerNames = performerNames;
	}
	public String getAuditerNames() {
		return auditerNames;
	}
	public void setAuditerNames(String auditerNames) {
		this.auditerNames = auditerNames;
	}
	public java.lang.String getProjectId() {
		return projectId;
	}
	public void setProjectId(java.lang.String projectId) {
		this.projectId = projectId;
	}
	

	

}