package cn.thd.pojo.plan;

import java.util.Date;

/**
 * cn.thd.pojo.plan.PlanItem entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class PlanItem implements java.io.Serializable {
	//PK   
	private java.lang.String planItemId;
	// 
	private java.lang.String planItemTitle;
	// 
	private java.lang.Integer currentProgress;
	// 
	private java.lang.String planCode;
	// 
	private java.util.Date creTime;
	// 
	private java.lang.String exeUser;
	private java.util.Date modTime;
	private java.util.Date planStartDate;
	private java.util.Date planFinishDate;
	private java.lang.String taskId;
	public java.lang.String getTaskId() {
		return taskId;
	}
	public void setTaskId(java.lang.String taskId) {
		this.taskId = taskId;
	}
	public void setPlanItemId(java.lang.String planItemId){
		this.planItemId = planItemId;
	}
	public java.lang.String getPlanItemId(){
		return this.planItemId;
	}
	public void setPlanItemTitle(java.lang.String planItemTitle){
		this.planItemTitle = planItemTitle;
	}
	public java.lang.String getPlanItemTitle(){
		return this.planItemTitle;
	}
	public void setCurrentProgress(java.lang.Integer currentProgress){
		this.currentProgress = currentProgress;
	}
	public java.lang.Integer getCurrentProgress(){
		return this.currentProgress;
	}
	public void setPlanCode(java.lang.String planCode){
		this.planCode = planCode;
	}
	public java.lang.String getPlanCode(){
		return this.planCode;
	}
	public void setCreTime(java.util.Date creTime){
		this.creTime = creTime;
	}
	public java.util.Date getCreTime(){
		return this.creTime;
	}
	public void setModTime(java.util.Date modTime){
		this.modTime = modTime;
	}
	public java.util.Date getModTime(){
		return this.modTime;
	}
	public java.util.Date getPlanStartDate() {
		return planStartDate;
	}
	public void setPlanStartDate(java.util.Date planStartDate) {
		this.planStartDate = planStartDate;
	}
	public java.util.Date getPlanFinishDate() {
		return planFinishDate;
	}
	public void setPlanFinishDate(java.util.Date planFinishDate) {
		this.planFinishDate = planFinishDate;
	}
	public java.lang.String getExeUser() {
		return exeUser;
	}
	public void setExeUser(java.lang.String exeUser) {
		this.exeUser = exeUser;
	}
	
	

}