package cn.thd.pojo.plan;

import java.util.Date;

/**
 * cn.thd.pojo.plan.PlanExecution entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class PlanExecution implements java.io.Serializable {
	//PK   
	private java.lang.String id;
	// 
	private java.lang.String planCode;
	//
	private java.lang.String workName;
	// 
	private java.lang.String planItemId;
	// 
	private java.lang.Integer planProgress;
	//
	private java.lang.Integer finishProgress;
	// 
	private java.lang.String planRemark;
	// 
	private java.util.Date creTime;
	// 
	private java.util.Date modTime;
	
	private java.lang.String taskId;
	private java.lang.String exeUser;

	public void setId(java.lang.String id){
		this.id = id;
	}
	public java.lang.String getId(){
		return this.id;
	}
	public void setPlanCode(java.lang.String planCode){
		this.planCode = planCode;
	}
	public java.lang.String getPlanCode(){
		return this.planCode;
	}
	public void setPlanItemId(java.lang.String planItemId){
		this.planItemId = planItemId;
	}
	public java.lang.String getPlanItemId(){
		return this.planItemId;
	}
	public void setPlanProgress(java.lang.Integer planProgress){
		this.planProgress = planProgress;
	}
	public java.lang.Integer getPlanProgress(){
		return this.planProgress;
	}
	public void setPlanRemark(java.lang.String planRemark){
		this.planRemark = planRemark;
	}
	public java.lang.String getPlanRemark(){
		return this.planRemark;
	}
	public java.util.Date getCreTime() {
		return creTime;
	}
	public void setCreTime(java.util.Date creTime) {
		this.creTime = creTime;
	}
	public java.util.Date getModTime() {
		return modTime;
	}
	public void setModTime(java.util.Date modTime) {
		this.modTime = modTime;
	}
	public java.lang.Integer getFinishProgress() {
		return finishProgress;
	}
	public void setFinishProgress(java.lang.Integer finishProgress) {
		this.finishProgress = finishProgress;
	}
	public java.lang.String getTaskId() {
		return taskId;
	}
	public void setTaskId(java.lang.String taskId) {
		this.taskId = taskId;
	}
	public java.lang.String getExeUser() {
		return exeUser;
	}
	public void setExeUser(java.lang.String exeUser) {
		this.exeUser = exeUser;
	}
	public java.lang.String getWorkName() {
		return workName;
	}
	public void setWorkName(java.lang.String workName) {
		this.workName = workName;
	}

}