package cn.thd.pojo.plan;

import java.util.Date;

/**
 * cn.thd.pojo.plan.PlanInfo entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class PlanInfo implements java.io.Serializable {
	//PK   
	private java.lang.String planCode;
	
	// 
	private java.lang.String planClassify;
	// 
	private java.lang.String planRemark;
	// 
	private java.lang.String finishRemark;
	// 
	private java.lang.Integer planYear;
	// 
	private java.lang.Integer planMonth;
	// 
	private java.lang.Integer planWeek;
	// 
	private java.util.Date startDate;
	// 
	private java.util.Date finishDate;
	// 
	private java.lang.String planStatus;
	// 
	private java.util.Date drawFinishTime;
	// 
	private java.util.Date creTime;
	
	public void setPlanCode(java.lang.String planCode){
		this.planCode = planCode;
	}
	public java.lang.String getPlanCode(){
		return this.planCode;
	}
	public void setPlanClassify(java.lang.String planClassify){
		this.planClassify = planClassify;
	}
	public java.lang.String getPlanClassify(){
		return this.planClassify;
	}
	public void setPlanRemark(java.lang.String planRemark){
		this.planRemark = planRemark;
	}
	public java.lang.String getPlanRemark(){
		return this.planRemark;
	}
	public void setFinishRemark(java.lang.String finishRemark){
		this.finishRemark = finishRemark;
	}
	public java.lang.String getFinishRemark(){
		return this.finishRemark;
	}
	public void setPlanYear(java.lang.Integer planYear){
		this.planYear = planYear;
	}
	public java.lang.Integer getPlanYear(){
		return this.planYear;
	}
	public void setPlanMonth(java.lang.Integer planMonth){
		this.planMonth = planMonth;
	}
	public java.lang.Integer getPlanMonth(){
		return this.planMonth;
	}
	public void setPlanWeek(java.lang.Integer planWeek){
		this.planWeek = planWeek;
	}
	public java.lang.Integer getPlanWeek(){
		return this.planWeek;
	}
	public void setStartDate(java.util.Date startDate){
		this.startDate = startDate;
	}
	public java.util.Date getStartDate(){
		return this.startDate;
	}
	public void setFinishDate(java.util.Date finishDate){
		this.finishDate = finishDate;
	}
	public java.util.Date getFinishDate(){
		return this.finishDate;
	}
	public void setPlanStatus(java.lang.String planStatus){
		this.planStatus = planStatus;
	}
	public java.lang.String getPlanStatus(){
		return this.planStatus;
	}
	public void setDrawFinishTime(java.util.Date drawFinishTime){
		this.drawFinishTime = drawFinishTime;
	}
	public java.util.Date getDrawFinishTime(){
		return this.drawFinishTime;
	}
	public java.util.Date getCreTime() {
		return creTime;
	}
	public void setCreTime(java.util.Date creTime) {
		this.creTime = creTime;
	}

	
	
	
	

}