package cn.thd.pojo.plan;


/**
 * cn.thd.pojo.plan.PlanSummary entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class PlanSummary implements java.io.Serializable {
	//PK  主键
	private java.lang.String id;
	//计划代码 计划代码
	private java.lang.String planCode;
	//项目ID 项目ID
	private java.lang.String projectId;
	//计划内容 计划内容
	private java.lang.String planContent;
	//计划总结 计划总结
	private java.lang.String planSummary;
	//本周项目进度
	private java.lang.Integer projectProgress;
	//计划总结附件ID
	private java.lang.String docAttachId;
	
	
	public void setPlanCode(java.lang.String planCode){
		this.planCode = planCode;
	}
	public java.lang.String getPlanCode(){
		return this.planCode;
	}
	public void setProjectId(java.lang.String projectId){
		this.projectId = projectId;
	}
	public java.lang.String getProjectId(){
		return this.projectId;
	}
	public void setPlanContent(java.lang.String planContent){
		this.planContent = planContent;
	}
	public java.lang.String getPlanContent(){
		return this.planContent;
	}
	public void setPlanSummary(java.lang.String planSummary){
		this.planSummary = planSummary;
	}
	public java.lang.String getPlanSummary(){
		return this.planSummary;
	}
	public java.lang.String getId() {
		return id;
	}
	public void setId(java.lang.String id) {
		this.id = id;
	}
	public java.lang.Integer getProjectProgress() {
		return projectProgress;
	}
	public void setProjectProgress(java.lang.Integer projectProgress) {
		this.projectProgress = projectProgress;
	}
	public java.lang.String getDocAttachId() {
		return docAttachId;
	}
	public void setDocAttachId(java.lang.String docAttachId) {
		this.docAttachId = docAttachId;
	}
	
	

}